LOGIN_INVALIDCREDENTIALS = 'Incorrect username or password!'
LOGOUT = 'You have successfully logged out.'
REGISTER_USERINVALID = 'Invalid username! Try another one.'
REGISTER_SUCCESS = 'User successfully registered.'
WELCOME_MESSAGE = 'Welcome to the "Ateneo" store!'
ADD_BOOK_SUCCESS = 'Book successfully added!'
ADD_AUTHOR_SUCCESS = 'Author successfully added!'
FILE_NOT_SUPPORTED = 'Please choose another image supported'
